# Run SonarScanner

name: SonarCloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    env:
      BUILD_WRAPPER_OUT_DIR: bw-output

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis

    - name: Install build-wrapper
      uses: SonarSource/sonarqube-scan-action/install-build-wrapper@2f77a1ec69fb1d595b06f35ab27e97605bdef703 # v5

    - name: Download Nordic SDK
      run: |
        if [ ! -d "nRF5_SDK_15.3.0_59ac345/modules" ]; then
          wget -q --max-redirect=0 https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v15.x.x/nRF5_SDK_15.3.0_59ac345.zip
          unzip -q nRF5_SDK_15.3.0_59ac345.zip
        fi

    - name: Compile project
      run: |
        build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} \
          gcc -c src/*.c -I./nRF5_SDK_15.3.0_59ac345/components/libraries/util -I./src

    - name: Set up Ruby
      uses: ruby/setup-ruby@d354de180d0c9e813cfddfcbdc079945d4be589b # v1.275.0
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Install Ceedling and GCovr
      run: |
        gem install ceedling
        pip install gcovr

    - name: Run tests
      run: make test_all_gcov

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@2f77a1ec69fb1d595b06f35ab27e97605bdef703 # v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=ruuvi
          -Dsonar.projectKey=ruuvi_ruuvi.endpoints.c
          -Dsonar.sources=./src
          -Dsonar.cfamily.build-wrapper-output=${{ env.BUILD_WRAPPER_OUT_DIR }}
          -Dsonar.cfamily.gcov.reportsPath=.
          -Dsonar.host.url=https://sonarcloud.io
